//! Output-kind extensions for synthetic generators: scalar-mode
//! `noise`, and sprite-mode `solid` / `circle` / `gradient-*`.
//! The scalar variants are validated by piping through `color-ramp`;
//! the sprite variants are validated by routing through `place` (a
//! Sprite consumer).

mod common;
use common::render;

#[test]
fn noise_scalar_renders_through_color_ramp() {
    // Tile-anchored value noise in scalar mode produces ~[-1, 1].
    // map-range normalises to [0, 1]; color-ramp then turns 0 → red,
    // 1 → blue. Centre of an 8-tile is a deterministic mid-grey-ish
    // value — we just check that *some* non-trivial pixel diversity
    // shows up (i.e., colour-ramp received valid scalar samples).
    let json = r##"{
      "name": "demo",
      "tile-size": 8,
      "nodes": {
        "n":    { "op": "noise", "type": "value", "kind": "scalar",
                  "scale-px": 4, "anchor": "tile", "seed": 0 },
        "norm": { "op": "map-range", "field": "@n",
                  "in-min": -1, "in-max": 1, "out-min": 0, "out-max": 1, "clamp": true },
        "out":  { "op": "color-ramp", "field": "@norm",
                  "stops": [ { "value": 0, "color": "#ff0000" },
                             { "value": 1, "color": "#0000ff" } ] }
      },
      "output": "@out"
    }"##;
    let r = render(json, 8, 0);
    // Across the 8×8 tile, we should see both red-ish and blue-ish
    // pixels (i.e., the scalar samples vary).
    let mut saw_red = false;
    let mut saw_blue = false;
    for y in 0..8 {
        for x in 0..8 {
            let p = r.pixel(x, y);
            if p[0] as i32 > p[2] as i32 + 40 {
                saw_red = true;
            }
            if p[2] as i32 > p[0] as i32 + 40 {
                saw_blue = true;
            }
        }
    }
    assert!(
        saw_red && saw_blue,
        "scalar noise should give a mix of low/high values"
    );
}

#[test]
fn solid_sprite_feeds_place_at_native_size() {
    // 16×16 red sprite generated by `solid`, then placed (fit cover)
    // onto a 32 canvas. Centre should be red.
    let json = r##"{
      "name": "demo",
      "tile-size": 32,
      "nodes": {
        "src": { "op": "solid", "color": "#ff0000",
                 "kind": "sprite", "width-px": 16, "height-px": 16 },
        "out": { "op": "place", "input": "@src", "fit": "cover" }
      },
      "output": "@out"
    }"##;
    let r = render(json, 32, 0);
    assert_eq!(r.pixel(16, 16), [0xff, 0x00, 0x00, 0xff]);
}

#[test]
fn circle_sprite_feeds_tiling() {
    // 16×16 sprite with a centred green disk, then tiled across a
    // 32 canvas. Centres of the four tiled positions should be green.
    let json = r##"{
      "name": "demo",
      "tile-size": 32,
      "nodes": {
        "src":  { "op": "circle", "color": "#00ff00",
                  "kind": "sprite", "width-px": 16, "height-px": 16,
                  "radius-frac": 0.4 },
        "out":  { "op": "tiling", "input": "@src", "anchor": "tile", "scale-px": 16 }
      },
      "output": "@out"
    }"##;
    let r = render(json, 32, 0);
    // Tiling at scale-px 16 places sprite copies at (8,8) and (24,24).
    let a = r.pixel(8, 8);
    let b = r.pixel(24, 24);
    assert!(a[1] > 200, "first tile centre should be green: {a:?}");
    assert!(b[1] > 200, "second tile centre should be green: {b:?}");
}

#[test]
fn gradient_linear_sprite_renders_at_native_size() {
    // 32-canvas, 16×16 horizontal red→blue linear sprite, placed cover.
    // Sprite top-left in sprite-local coords is red; bottom-right is blue.
    // Under cover, sprite-(0,0) maps to canvas-(0,0) and sprite-(15,15)
    // maps to canvas-(31,31). So canvas left edge should be red, right
    // edge blue.
    let json = r##"{
      "name": "demo",
      "tile-size": 32,
      "nodes": {
        "g":   { "op": "gradient-linear",
                 "start": [0.0, 0.5], "end": [1.0, 0.5],
                 "kind": "sprite", "width-px": 16, "height-px": 16,
                 "stops": [[0.0, "#ff0000"], [1.0, "#0000ff"]] },
        "out": { "op": "place", "input": "@g", "fit": "stretch" }
      },
      "output": "@out"
    }"##;
    let r = render(json, 32, 0);
    let left = r.pixel(1, 16);
    let right = r.pixel(30, 16);
    assert!(
        left[0] > 200 && left[2] < 40,
        "left edge should be red: {left:?}"
    );
    assert!(
        right[2] > 200 && right[0] < 40,
        "right edge should be blue: {right:?}"
    );
}
