#!/usr/bin/env bash
# Print the Homebrew formula for the `ezu` CLI, pinned to the archives of
# one release. The release workflow runs this against the artifacts it is
# about to attach, so the checksums describe the very bytes it uploads.
#
#   scripts/brew-formula.sh v0.9.0 dist/ > Formula/ezu.rb
#
# `dist/` is expected to hold the four Unix archives named as the release
# workflow names them: ezu-<tag>-<target>.tar.gz. Windows ships a .zip and
# has no Homebrew story, so it is not referenced here.
set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "usage: $0 <tag> <dist-dir>" >&2
  exit 2
fi

tag=$1
dist=$2
base="https://github.com/reearth/ezu/releases/download/$tag"

# Linux runners have sha256sum, macOS has shasum; this script runs on both
# because it is also how you regenerate the formula by hand.
sha256() {
  if command -v sha256sum > /dev/null 2>&1; then
    sha256sum "$1" | cut -d ' ' -f 1
  else
    shasum -a 256 "$1" | cut -d ' ' -f 1
  fi
}

# Emit one `url`/`sha256` pair for a target, indented to sit inside the
# on_macos/on_linux + on_arm/on_intel blocks.
slice() {
  local target=$1 indent=$2
  local file="$dist/ezu-$tag-$target.tar.gz"
  if [ ! -f "$file" ]; then
    echo "missing archive: $file" >&2
    exit 1
  fi
  printf '%surl "%s/ezu-%s-%s.tar.gz"\n' "$indent" "$base" "$tag" "$target"
  printf '%ssha256 "%s"\n' "$indent" "$(sha256 "$file")"
}

cat <<EOF
# Generated by scripts/brew-formula.sh in reearth/ezu — do not edit.
class Ezu < Formula
  desc "Command-line renderer for the Ezu Style Spec"
  homepage "https://github.com/reearth/ezu"
  version "${tag#v}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
$(slice aarch64-apple-darwin '      ')
    end
    on_intel do
$(slice x86_64-apple-darwin '      ')
    end
  end

  on_linux do
    on_arm do
$(slice aarch64-unknown-linux-gnu '      ')
    end
    on_intel do
$(slice x86_64-unknown-linux-gnu '      ')
    end
  end

  def install
    bin.install "ezu"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ezu --version")
  end
end
EOF
