[package]
name = "ezu-paint"
description = "Paint MVT features onto a hokusai surface for ezu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
ezu-core = { workspace = true }
ezu-graph = { workspace = true }
ezu-mvt = { workspace = true }
ezu-style = { workspace = true }
serde_json = { workspace = true }
xxhash-rust = { workspace = true }
hokusai = { workspace = true, features = ["myb-json", "tile-mem", "tiny-skia"] }
tiny-skia = { workspace = true }
libblur = { workspace = true }
thiserror = { workspace = true }
